//! `.omnilens/manifest.json` — AI-discoverable project specification.
//!
//! When an AI agent enters a project directory and finds `.omnilens/manifest.json`,
//! it knows:
//! 1. This project uses omnilens for verification
//! 2. What commands are available and how to call them
//! 3. What protocol to use for structured communication
//! 4. What rules to follow when modifying code
//!
//! The manifest is auto-generated by `omnilens init` and updated by `omnilens index`.

use std::path::Path;

use anyhow::Result;
use serde::{Deserialize, Serialize};

/// The manifest file path relative to project root.
pub const MANIFEST_PATH: &str = ".omnilens/manifest.json";

#[derive(Debug, Serialize, Deserialize)]
pub struct Manifest {
    /// Manifest schema version.
    pub version: String,

    /// Project information discovered by omnilens.
    pub project: ProjectInfo,

    /// Available omnilens commands the AI can use.
    pub commands: Vec<CommandSpec>,

    /// Structured protocol for AI ↔ omnilens communication.
    pub protocol: ProtocolSpec,

    /// Rules the AI must follow when working in this project.
    pub rules: Vec<Rule>,

    /// Current project health snapshot (updated on each index).
    pub health: Option<HealthSnapshot>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct ProjectInfo {
    pub languages: Vec<String>,
    pub files: usize,
    pub functions: usize,
    pub types: usize,
    pub last_indexed: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct CommandSpec {
    /// Command name.
    pub name: String,
    /// What it does (for AI to decide when to use it).
    pub purpose: String,
    /// How to call it.
    pub usage: String,
    /// Output format.
    pub output: String,
    /// When the AI should call this.
    pub when: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct ProtocolSpec {
    /// How to send structured requests to omnilens.
    pub request_format: String,
    /// How to read structured responses.
    pub response_format: String,
    /// JSON schema URL for verify output.
    pub verify_schema: String,
    /// JSON schema URL for fix request/response.
    pub fix_protocol: FixProtocol,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct FixProtocol {
    pub description: String,
    pub request_example: serde_json::Value,
    pub response_example: serde_json::Value,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Rule {
    pub id: String,
    pub description: String,
    pub severity: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct HealthSnapshot {
    pub score: u32,
    pub total_functions: usize,
    pub total_types: usize,
    pub high_complexity_count: usize,
    pub invariants_discovered: usize,
}

/// Generate a manifest for the project.
pub fn generate(
    project_root: &Path,
    graph: &omnilens_graph::SemanticGraph,
) -> Manifest {
    use omnilens_ir::node::UsirNode;
    use omnilens_ir::Visibility;

    let all_ids = graph.all_node_ids();

    // Count stats.
    let mut languages = std::collections::HashSet::new();
    let mut files = std::collections::HashSet::new();
    let mut functions = 0usize;
    let mut types = 0usize;
    let mut high_complexity = 0usize;

    for id in &all_ids {
        let Some(node) = graph.get_node(*id) else { continue };
        if graph.is_placeholder(*id) { continue; }

        let file = node.span().file.to_string_lossy().replace('\\', "/");
        files.insert(file.clone());

        let ext = file.rsplit('.').next().unwrap_or("");
        match ext {
            "rs" => { languages.insert("Rust"); }
            "ts" | "tsx" | "js" | "jsx" => { languages.insert("TypeScript"); }
            "py" => { languages.insert("Python"); }
            _ => {}
        }

        match node {
            UsirNode::Function(f) if f.complexity.is_some() => {
                functions += 1;
                if f.complexity.unwrap_or(0) > 15 {
                    high_complexity += 1;
                }
            }
            UsirNode::DataType(_) => { types += 1; }
            _ => {}
        }
    }

    let invs = crate::invariants::discover(graph);

    let complexity_penalty = (high_complexity as f64 * 3.0).min(30.0);
    let health_score = (100.0 - complexity_penalty).max(0.0) as u32;

    let now = chrono::Utc::now().to_rfc3339();

    Manifest {
        version: "1".to_string(),
        project: ProjectInfo {
            languages: languages.into_iter().map(|s| s.to_string()).collect(),
            files: files.len(),
            functions,
            types,
            last_indexed: Some(now),
        },
        commands: vec![
            CommandSpec {
                name: "omnilens check".into(),
                purpose: "Scan code changes for problems: breaking changes, missing tests, complexity spikes.".into(),
                usage: "omnilens check [files...]".into(),
                output: "Grouped issues by file with severity and suggested actions.".into(),
                when: "ONCE after completing a logical unit of work, before committing. NOT after every individual edit.".into(),
            },
            CommandSpec {
                name: "omnilens fix".into(),
                purpose: "Auto-generate tests for untested functions and run them.".into(),
                usage: "omnilens fix [files...]".into(),
                output: "Generated test files + test execution results.".into(),
                when: "ONCE when omnilens check reports missing tests. Do not loop — fix handles retries internally.".into(),
            },
            CommandSpec {
                name: "omnilens fix --auto".into(),
                purpose: "Generate tests, run them, and fix failures in an internal loop. AI should NOT wrap this in another loop.".into(),
                usage: "omnilens fix --auto --max-retries 3".into(),
                output: "Iterative test generation and fixing until all pass.".into(),
                when: "ONCE when tests are failing. This command loops internally — do NOT retry it yourself.".into(),
            },
            CommandSpec {
                name: "omnilens verify --format json --diff <ref>".into(),
                purpose: "Get structured verification results as JSON.".into(),
                usage: "omnilens --format json verify --diff HEAD~1".into(),
                output: "JSON with risk_score, semantic_changes, invariant_warnings, suggested_tests.".into(),
                when: "When you need machine-readable analysis of code changes.".into(),
            },
            CommandSpec {
                name: "omnilens query".into(),
                purpose: "Search codebase semantically with OmniQL.".into(),
                usage: r#"omnilens query "FIND functions WHERE complexity > 10""#.into(),
                output: "List of matching nodes with file, line, name, description.".into(),
                when: "When you need to understand the codebase structure or find specific patterns.".into(),
            },
            CommandSpec {
                name: "omnilens impact".into(),
                purpose: "Analyze blast radius of changing a function.".into(),
                usage: "omnilens impact <file> --fn <name>".into(),
                output: "Callers and callees with depth and risk score.".into(),
                when: "Before modifying a function, to understand what might break.".into(),
            },
            CommandSpec {
                name: "omnilens status".into(),
                purpose: "Project health dashboard.".into(),
                usage: "omnilens status".into(),
                output: "Health score, hotspots, discovered rules.".into(),
                when: "To get an overview of the project state.".into(),
            },
        ],
        protocol: ProtocolSpec {
            request_format: "JSON via stdin or file".into(),
            response_format: "JSON via stdout".into(),
            verify_schema: "https://github.com/injaehwang/omnilens/blob/main/schemas/verify-output.schema.json".into(),
            fix_protocol: FixProtocol {
                description: "Send a FixRequest, receive a FixResponse. AI modifies test files only.".into(),
                request_example: serde_json::json!({
                    "task": "Fix failing tests",
                    "failures": [{"test_name": "test_login", "file": "test_auth.py", "error_type": "AssertionError", "error_message": "None is not None"}],
                    "test_files": [{"path": "test_auth.py", "content": "...", "readonly": false}],
                    "source_files": [{"path": "auth.py", "content": "...", "readonly": true}],
                    "rules": ["Only modify test files"]
                }),
                response_example: serde_json::json!({
                    "edits": [{"path": "test_auth.py", "content": "...fixed content..."}],
                    "explanation": "Fixed mock setup for login function"
                }),
            },
        },
        rules: generate_rules(graph),
        health: Some(HealthSnapshot {
            score: health_score,
            total_functions: functions,
            total_types: types,
            high_complexity_count: high_complexity,
            invariants_discovered: invs.stats.invariants_found,
        }),
    }
}

fn generate_rules(graph: &omnilens_graph::SemanticGraph) -> Vec<Rule> {
    let invs = crate::invariants::discover(graph);
    let mut rules = Vec::new();

    // Always include base rules.
    rules.push(Rule {
        id: "when-to-check".into(),
        description: "Run `omnilens check` ONCE when your task is complete, before committing. Do NOT run it after every individual edit — only when you are done with a logical unit of work.".into(),
        severity: "required".into(),
    });
    rules.push(Rule {
        id: "fix-loop".into(),
        description: "If `omnilens check` reports issues, run `omnilens fix --auto` ONCE. The fix loop handles retries internally. Do NOT call check or fix again yourself — wait for the loop to finish.".into(),
        severity: "required".into(),
    });
    rules.push(Rule {
        id: "no-infinite-loop".into(),
        description: "NEVER call omnilens inside a loop you control. The workflow is: (1) do your work, (2) omnilens check, (3) if needed omnilens fix --auto, (4) commit. That's it. Three steps maximum.".into(),
        severity: "required".into(),
    });
    rules.push(Rule {
        id: "no-breaking-without-review".into(),
        description: "Do not introduce breaking changes (public API signature changes) without flagging for review.".into(),
        severity: "required".into(),
    });
    rules.push(Rule {
        id: "test-new-functions".into(),
        description: "Every new public function must have at least one test. Use `omnilens fix` to generate.".into(),
        severity: "required".into(),
    });

    // Add discovered invariants as rules.
    for inv in &invs.invariants {
        if inv.confidence >= 0.9 {
            rules.push(Rule {
                id: format!("invariant-{}", inv.id.0),
                description: inv.description.clone(),
                severity: "warning".into(),
            });
        }
    }

    rules
}

/// Write manifest to .omnilens/manifest.json.
pub fn write(project_root: &Path, manifest: &Manifest) -> Result<()> {
    let dir = project_root.join(".omnilens");
    std::fs::create_dir_all(&dir)?;

    let path = project_root.join(MANIFEST_PATH);
    let json = serde_json::to_string_pretty(manifest)?;
    std::fs::write(&path, json)?;
    Ok(())
}

/// Read manifest from .omnilens/manifest.json.
pub fn read(project_root: &Path) -> Result<Option<Manifest>> {
    let path = project_root.join(MANIFEST_PATH);
    if !path.exists() {
        return Ok(None);
    }
    let content = std::fs::read_to_string(&path)?;
    let manifest: Manifest = serde_json::from_str(&content)?;
    Ok(Some(manifest))
}
